### ISSUE TITLE
Attribute the proper licenses to all the projects we use

### ISSUE THREAD

**Issue by jgoux** [snaplet/postgres-wasm#14]
We need to properly attribute the licenses for all the libraries we are using.

**Comment by peterp** [comment]
@jgoux Can you look into this? I'm assuming that something that we're using requires attribution?

**Comment by jgoux** [comment]
Yes, we have to launch a special command when building buildroot that will gather all the licenses automatically. 👍

**Comment by peterp** [comment]
Could you do that for us?

**Comment by burggraf** [comment]
I'm doing a build this morning.  I can run that.

**Comment by jgoux** [comment]
> I'm doing a build this morning. I can run that.

Thanks Mark! 🙇‍♂️

**Comment by burggraf** [comment]
I created a branch for this `chore/licenses`.

**Comment by jgoux** [comment]
It's on main, thanks again @burggraf ! 🏅
