### ISSUE TITLE
Up/Down arrows aren't working in psql

### ISSUE THREAD

**Issue by jgoux** [snaplet/postgres-wasm#29]
Currently when entering up and down arrows, it prints something in the terminal instead of moving backward/forward with the history. It only happens when in `psql` prompt.

I guess we'll have to intercept inputs when we detect that we're in `psql` (the hint would be that the line begins with `postgres=#`) and swap the input to a proper one.

**Comment by burggraf** [comment]
https://www.postgresql.org/message-id/71E8BF64-1659-427A-A5B6-C88727E80EA1%40seespotcode.net

I'm testing a build with the readline package included now to see if this works.

**Comment by burggraf** [comment]
Confirmed:  setting these options in `make menuconfig` fixes this:
`Target packages / Libraries / Text & Terminal Handling / readline (both options)`
