### ISSUE TITLE
Is there a way to use postgres-wasm with node for tests ?

### ISSUE THREAD

**Issue by a7ul** [snaplet/postgres-wasm#39]
Hi, 
Is there a way to run postgres-wasm in node for testing purposes?
Wanted to see if I can somehow use this module to run an in memory postgres that is easier to create and destroy between test cases.

**Comment by burggraf** [comment]
Our current implementation isn't really appropriate for this use case.  This is not a "pure wasm implementation of PostgreSQL", but rather we're booting a full linux environment and running PostgreSQL inside of that.

**Comment by peterp** [comment]
I'm going to close this, please open it again if you want to try an experiment!
