### ISSUE TITLE
How to build the wasm with custome?

### ISSUE THREAD

**Issue by FreeGIS** [snaplet/postgres-wasm#42]
when i run sql:  create extension postgis;   the postgres-wasm is not enable.  Can you tell me how to build the custome with  vm？
example:https://www.crunchydata.com/blog/crazy-idea-to-postgres-in-the-web-browser

**Comment by burggraf** [comment]
You will need to add `postgis` with `buildroot` by using `make menuconfig` and adding it to your configuration.  We will be adding `postgis` in a future version of `postgres-wasm`.
